blueprint:
  name: Water Leak Warning
  description: >-
    Warns every hour via speakers and mobile notifications if water is detected
    and sends a notification if the sensor is unavailable.
  domain: automation
  input:
    sensor:
      name: Water Leak Sensor
      description: Select the water leak sensor to monitor.
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
    media_player:
      name: Speaker
      description: Select the speaker to use for the warning.
      selector:
        entity:
          domain: media_player
    notify_device:
      name: Notification Device
      description: Select the device to receive mobile notifications.
      selector:
        device:
    repeat_count:
      name: Repeat Count
      description: Number of times the warnings should be repeated.
      default: 5
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: times
    media_content_id:
      name: Media Content ID
      description: URL to the media file to play.
      default: http://192.168.1.166:8123/local/imperial-alert.mp3
      selector:
        text:
    volume_level:
      name: Volume Level
      description: Volume level for the warning.
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
          unit_of_measurement: level

trigger:
  - platform: time_pattern
    hours: /1

condition:
  - condition: state
    entity_id: !input sensor
    state: "on"

action:
  - repeat:
      while:
        - condition: state
          entity_id: !input sensor
          state: "on"
        - condition: template
          value_template: "{{ repeat.index <= !input repeat_count }}"
      sequence:
        - service: media_player.volume_set
          data:
            entity_id: !input media_player
            volume_level: !input volume_level
        - service: media_player.play_media
          data:
            entity_id: !input media_player
            media_content_id: !input media_content_id
            media_content_type: music
        - delay: "00:00:10"
        - service: tts.google_translate_say
          data:
            entity_id: !input media_player
            message: "Warning! Water detected at {{ state_attr('!input sensor', 'friendly_name') }}"
            language: en
        - service: notify.mobile_app
          data:
            target: !input notify_device
            title: "🚨 WATER LEAK - {{ state_attr('!input sensor', 'friendly_name') }}"
            message: "Sensor has detected a water leak. Check immediately!"
            data:
              push:
                sound:
                  name: default
                  critical: 1
                  volume: 1
        - service: browser_mod.popup
          data:
            title: "🚨 WATER LEAK"
            content:
              type: markdown
              content: >
                ## ⛺ Leak detected!
                **Location:** `{{ states('!input sensor') }}`
            deviceID:
              - this
            style:
              width: 400px
              background: red
              color: white
              font-size: 20px
        - delay: "00:00:15"
        - service: browser_mod.close_popup
        - delay: "00:01:00"
  - condition: template
    value_template: "{{ states('!input sensor') == 'unavailable' }}"
  - service: notify.mobile_app
    data:
      target: !input notify_device
      title: "🚨 SENSOR UNAVAILABLE - {{ state_attr('!input sensor', 'friendly_name') }}"
      message: "The water leak sensor at {{ state_attr('!input sensor', 'friendly_name') }} is currently unavailable. Check immediately!"
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1

mode: single
